version: "3"

volumes:
  node_modules:
services:
  my-app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: zenless_api_dev
    ports:
      - "3001:3001"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
