ARG NODE_VERSION=18.14.2

FROM node:${NODE_VERSION}-slim as base

ARG PORT=3001

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY package.json package-lock.json .
RUN npm install

# Run
FROM base

ENV PORT=$PORT

COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]